import type { IContentAircraftTable, IDataSource } from '@shared/types';

export const aircraftMock: IDataSource<IContentAircraftTable> = {
  content: [
    {
      id: 1821,
      aircraftNumber: 'POlI',
      model: 'A37890',
      modelYear: 2006,
      flightRange: 16899,
    },
    {
      id: 1767,
      aircraftNumber: '1234-XYZ!',
      model: 'McDonnell douglas f/a-18 hornet',
      modelYear: 2003,
      flightRange: 7800,
    },
    {
      id: 1799,
      aircraftNumber: 'СО97777',
      model: '~@#$%^&',
      modelYear: 2004,
      flightRange: 2,
    },
    {
      id: 1951,
      aircraftNumber: '14881',
      model: '322',
      modelYear: 2001,
      flightRange: 5,
    },
    {
      id: 1005,
      aircraftNumber: 'fm34',
      model: 'string',
      modelYear: 2000,
      flightRange: 0,
    },
    {
      id: 7,
      aircraftNumber: '444400',
      model: 'Boeing 737',
      modelYear: 2010,
      flightRange: 11700,
    },
    {
      id: 1007,
      aircraftNumber: 'fm36',
      model: 'string',
      modelYear: 2000,
      flightRange: 0,
    },
    {
      id: 1008,
      aircraftNumber: 'fm37',
      model: 'string',
      modelYear: 2000,
      flightRange: 0,
    },
    {
      id: 1009,
      aircraftNumber: 'fm38',
      model: 'string',
      modelYear: 2000,
      flightRange: 0,
    },
    {
      id: 1010,
      aircraftNumber: 'fm39',
      model: 'string',
      modelYear: 2000,
      flightRange: 0,
    },
    {
      id: 1011,
      aircraftNumber: 'fm40',
      model: 'string',
      modelYear: 2000,
      flightRange: 0,
    },
    {
      id: 1012,
      aircraftNumber: 'fm41',
      model: 'string',
      modelYear: 2000,
      flightRange: 0,
    },
    {
      id: 1013,
      aircraftNumber: 'fm43',
      model: 'string',
      modelYear: 2000,
      flightRange: 0,
    },
    {
      id: 1014,
      aircraftNumber: 'fm44',
      model: 'string',
      modelYear: 2000,
      flightRange: 0,
    },
    {
      id: 1015,
      aircraftNumber: 'fm45',
      model: 'string',
      modelYear: 2000,
      flightRange: 0,
    },
    {
      id: 1016,
      aircraftNumber: 'fm46',
      model: 'string',
      modelYear: 2000,
      flightRange: 0,
    },
    {
      id: 1017,
      aircraftNumber: 'fm47',
      model: 'string',
      modelYear: 2000,
      flightRange: 0,
    },
    {
      id: 6,
      aircraftNumber: 'test3',
      model: 'string',
      modelYear: 2000,
      flightRange: 0,
    },
    {
      id: 1018,
      aircraftNumber: 'fm48',
      model: 'string',
      modelYear: 2000,
      flightRange: 0,
    },
    {
      id: 1114,
      aircraftNumber: '151515',
      model: 'dangerous 3000',
      modelYear: 2200,
      flightRange: 1515361,
    },
    {
      id: 8,
      aircraftNumber: '234567непра',
      model: 'string',
      modelYear: 2000,
      flightRange: 0,
    },
    {
      id: 1020,
      aircraftNumber: 'fm50',
      model: 'string',
      modelYear: 2000,
      flightRange: 0,
    },
    {
      id: 1021,
      aircraftNumber: 'fm51',
      model: 'string',
      modelYear: 2000,
      flightRange: 0,
    },
    {
      id: 1970,
      aircraftNumber: '2222211',
      model: 'string',
      modelYear: 2020,
      flightRange: 1,
    },
    {
      id: 1023,
      aircraftNumber: 'fm53',
      model: 'string',
      modelYear: 2000,
      flightRange: 0,
    },
    {
      id: 1024,
      aircraftNumber: 'fm54',
      model: 'string',
      modelYear: 2000,
      flightRange: 0,
    },
    {
      id: 1025,
      aircraftNumber: 'fm55',
      model: 'string',
      modelYear: 2000,
      flightRange: 0,
    },
    {
      id: 1026,
      aircraftNumber: 'fm56',
      model: 'string',
      modelYear: 2000,
      flightRange: 0,
    },
    {
      id: 1027,
      aircraftNumber: 'fm57',
      model: 'string',
      modelYear: 2000,
      flightRange: 0,
    },
    {
      id: 1028,
      aircraftNumber: 'fm58',
      model: 'string',
      modelYear: 2000,
      flightRange: 0,
    },
  ],
  pageable: {
    pageNumber: 1,
    pageSize: 10,
    sort: [],
    offset: 10,
    paged: true,
    unpaged: false,
  },
  totalPages: 44,
  totalElements: 439,
  last: false,
  number: 1,
  size: 10,
  numberOfElements: 10,
  sort: [],
  first: false,
  empty: false,
};
