import type { IDataSource } from '../models/types.ts';

export const destinationMock: IDataSource = {
  content: [
    {
      id: 6,
      airportCode: 'SVX',
      timezone: 'GMT +5',
      countryName: 'Россия',
      cityName: 'Екатеринбург',
      airportName: 'Кольцово',
    },
    {
      id: 7,
      airportCode: 'AAQ',
      timezone: 'GMT +3',
      countryName: 'Россия',
      cityName: 'Анапа',
      airportName: 'Витязево',
    },
    {
      id: 8,
      airportCode: 'ARH',
      timezone: 'GMT +3',
      countryName: 'Россия',
      cityName: 'Архангельск',
      airportName: 'Талаги',
    },
    {
      id: 9,
      airportCode: 'KGD',
      timezone: 'GMT +2',
      countryName: 'Россия',
      cityName: 'Калининград',
      airportName: 'Калининград',
    },
    {
      id: 10,
      airportCode: 'KRR',
      timezone: 'GMT +3',
      countryName: 'Россия',
      cityName: 'Краснодар',
      airportName: 'Пашковский',
    },
    {
      id: 11,
      airportCode: 'KLD',
      timezone: 'GMT +3',
      countryName: 'Россия',
      cityName: 'Тверь',
      airportName: 'Мигалово',
    },
    {
      id: 12,
      airportCode: 'KLF',
      timezone: 'GMT +3',
      countryName: 'Россия',
      cityName: 'Калуга',
      airportName: 'Калуга',
    },
    {
      id: 13,
      airportCode: 'KZN',
      timezone: 'GMT +3',
      countryName: 'Россия',
      cityName: 'Казань',
      airportName: 'Казань',
    },
    {
      id: 14,
      airportCode: 'KMW',
      timezone: 'GMT +3',
      countryName: 'Россия',
      cityName: 'Кострома',
      airportName: 'Кострома',
    },
    {
      id: 15,
      airportCode: 'KUF',
      timezone: 'GMT +4',
      countryName: 'Россия',
      cityName: 'Самара',
      airportName: 'Курумоч',
    },
    {
      id: 16,
      airportCode: 'IAR',
      timezone: 'GMT +3',
      countryName: 'Россия',
      cityName: 'Ярославль',
      airportName: 'Туношна',
    },
    {
      id: 17,
      airportCode: 'IWA',
      timezone: 'GMT +3',
      countryName: 'Россия',
      cityName: 'Иваново',
      airportName: 'Иваново',
    },
    {
      id: 18,
      airportCode: 'GRV',
      timezone: 'GMT +3',
      countryName: 'Россия',
      cityName: 'Грозный',
      airportName: 'Грозный',
    },
    {
      id: 19,
      airportCode: 'IJK',
      timezone: 'GMT +4',
      countryName: 'Россия',
      cityName: 'Ижевск',
      airportName: 'Ижевск',
    },
    {
      id: 20,
      airportCode: 'GOJ',
      timezone: 'GMT +3',
      countryName: 'Россия',
      cityName: 'Нижний Новгород',
      airportName: 'Нижний Новгород',
    },
    {
      id: 21,
      airportCode: 'LPK',
      timezone: 'GMT +3',
      countryName: 'Россия',
      cityName: 'Липецк',
      airportName: 'Липецк',
    },
    {
      id: 22,
      airportCode: 'NAL',
      timezone: 'GMT +3',
      countryName: 'Россия',
      cityName: 'Нальчик',
      airportName: 'Нальчик',
    },
    {
      id: 1,
      airportCode: 'VKO',
      timezone: 'GMT +3',
      countryName: 'Россия',
      cityName: 'Москва',
      airportName: 'Внуково',
    },
    {
      id: 2,
      airportCode: 'VOG',
      timezone: 'GMT +3',
      countryName: 'Россия',
      cityName: 'Волгоград',
      airportName: 'Гумрак',
    },
    {
      id: 3,
      airportCode: 'MQF',
      timezone: 'GMT +5',
      countryName: 'Россия',
      cityName: 'Магнитогорск',
      airportName: 'Магнитогорск',
    },
    {
      id: 4,
      airportCode: 'OMS',
      timezone: 'GMT +6',
      countryName: 'Россия',
      cityName: 'Омск',
      airportName: 'Омск',
    },
    {
      id: 23,
      airportCode: 'DME',
      timezone: 'GMT +3',
      countryName: 'Россия',
      cityName: 'Москва',
      airportName: 'Домодедово',
    },
    {
      id: 24,
      airportCode: 'OVB',
      timezone: 'GMT +7',
      countryName: 'Россия',
      cityName: 'Новосибирск',
      airportName: 'Толмачёво',
    },
    {
      id: 25,
      airportCode: 'PKC',
      timezone: 'GMT +12',
      countryName: 'Россия',
      cityName: 'Петропавловск-Камчатский',
      airportName: 'Елизово',
    },
    {
      id: 1016,
      airportCode: 'TYD',
      timezone: 'UTC+9',
      countryName: 'Россия',
      cityName: 'Тында',
      airportName: 'Тында',
    },
  ],
  pageable: 'INSTANCE',
  totalPages: 1,
  totalElements: 25,
  last: true,
  number: 0,
  size: 25,
  numberOfElements: 25,
  sort: [],
  first: true,
  empty: false,
};
